version: 1      # do not change this, unless if you want your config to regenerate

useMySQL: false # currently not implemented

MySQL:
    username:   # insert MySQL login info here
    password: 


# worlds to control
worlds:
    - world
 