name: GameZones
description: A plugin that allows players to divide the world into areas with different gamemodes.
website: http://yoerik.com/bukkit/GameZones/

main: com.yoerik.GameZones.Main

version: 0.1
author: Widakay
authors: [Widakay, Pokemon649]

database: true
depend: [WorldEdit]

commands:
   gz:
      description: GameZones main command.
      usage: /gz help
      permission: GameZones.main
      permission-message: You don't have permission to use GameZones.